### ISSUE TITLE
TASK: Implement create client account page

### ISSUE THREAD

**Issue by vitogalv** [CSE442-Project/CSE-442-Project#24]
**Page Composition**
- Title to let user know they're creating a new client account
- Fields to capture following:
    - username
    - firstname
    - lastname
    - address
    - payment method
    - password
    - email
    - phone
    - driveway size
- Submit button that brings user to verification page

**HTML FILE:** https://github.com/CSE442-Project/CSE-442-Project/blob/develop/logic/accounts/templates/accounts/create_client.html

**Comment by smbond2** [comment]
Acceptance Tests:
-Data can be entered in every field option
-The submit button leads to the verification page when clicked
-All data in the fields is entered and saved into the database for future access(not necessary for Sprint 1)
