### ISSUE TITLE
TASK: Implement account creation verification page

### ISSUE THREAD

**Issue by vitogalv** [CSE442-Project/CSE-442-Project#28]
**Page Composition**
A message telling the user by name that their account was created successfully

**HTML FILE:** https://github.com/CSE442-Project/CSE-442-Project/blob/develop/logic/accounts/templates/accounts/create_verification.html

**Comment by smbond2** [comment]
Acceptance Test:
-The new users name is displayed on the page
-A message is showing that says an account was created successfully
